const commends = {
    setNickname : "setNickname",
    newUser : "newUser",
    connect : "connect",
    disconnect : "disconnect",
    disconnected : "disconnected",
    sendMsg : "sendMsg",
    newMsg : "newMsg",
    beginPath: "beginPath",
    strokePath : "strokePath",
    beganPath : "beganPath",
    strokedPath : "strokedPath",
    fill : "fill",
    playerUpdate : "playerUpdate",
    gameStarted:"gameStarted",
    painterNotif:"painterNotif",
    gameEnded: "gameEnded",
    gameStarting:"gameStarting",
    nicknameConfirm:"nicknameConfirm",
    countDown:"countDown",
    userList:"userList",
    disablePaint:"disablePaint",
    enablePaint:"enablePaint",
}

export default commends